In [0]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

import numpy as np
import pandas as pd

header = ['user_id', 'item_id', 'rating', 'timestamp']
drivePrefix = '/content/gdrive/My Drive/'
driveSuffix = '1301170092_MF_Movielens/ratings.csv'
df = pd.read_csv(drivePrefix + driveSuffix, sep=',', names =header, skiprows=1)

n_users = df.user_id.unique().shape[0]
n_items = df.item_id.unique().shape[0]
print('Number of users = ' + str(n_users) + ' | number of movies = ' + str(n_items))
print(df)

Mounted at /content/gdrive
Number of users = 610 | number of movies = 9724
        user_id  item_id  rating   timestamp
0             1        1     4.0   964982703
1             1        3     4.0   964981247
2             1        6     4.0   964982224
3             1       47     5.0   964983815
4             1       50     5.0   964982931
...         ...      ...     ...         ...
100831      610   166534     4.0  1493848402
100832      610   168248     5.0  1493850091
100833      610   168250     5.0  1494273047
100834      610   168252     5.0  1493846352
100835      610   170875     3.0  1493846415

[100836 rows x 4 columns]


In [0]:
users = df.user_id.unique()  # get unique user_id
print(users)
print(len(users))
items = df.item_id.unique()  # get unique item_id
print(items)
print(len(items))

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 24

In [0]:
npMovielens = df.to_numpy()
print(npMovielens)

userId = 2  # ganti saja user IDnya
print(npMovielens[npMovielens[:,0] == userId]) # select specific data based on user id

[[1.00000000e+00 1.00000000e+00 4.00000000e+00 9.64982703e+08]
 [1.00000000e+00 3.00000000e+00 4.00000000e+00 9.64981247e+08]
 [1.00000000e+00 6.00000000e+00 4.00000000e+00 9.64982224e+08]
 ...
 [6.10000000e+02 1.68250000e+05 5.00000000e+00 1.49427305e+09]
 [6.10000000e+02 1.68252000e+05 5.00000000e+00 1.49384635e+09]
 [6.10000000e+02 1.70875000e+05 3.00000000e+00 1.49384642e+09]]
[[2.00000000e+00 3.18000000e+02 3.00000000e+00 1.44571484e+09]
 [2.00000000e+00 3.33000000e+02 4.00000000e+00 1.44571503e+09]
 [2.00000000e+00 1.70400000e+03 4.50000000e+00 1.44571523e+09]
 [2.00000000e+00 3.57800000e+03 4.00000000e+00 1.44571488e+09]
 [2.00000000e+00 6.87400000e+03 4.00000000e+00 1.44571495e+09]
 [2.00000000e+00 8.79800000e+03 3.50000000e+00 1.44571496e+09]
 [2.00000000e+00 4.69700000e+04 4.00000000e+00 1.44571501e+09]
 [2.00000000e+00 4.85160000e+04 4.00000000e+00 1.44571506e+09]
 [2.00000000e+00 5.85590000e+04 4.50000000e+00 1.44571514e+09]
 [2.00000000e+00 6.07560000e+04 5.00000000e+00 1.

In [0]:
itemId = 3
print(npMovielens[npMovielens[:,1] == itemId]) # select specific data based on movie id

[[1.00000000e+00 3.00000000e+00 4.00000000e+00 9.64981247e+08]
 [6.00000000e+00 3.00000000e+00 5.00000000e+00 8.45554296e+08]
 [1.90000000e+01 3.00000000e+00 3.00000000e+00 9.65707636e+08]
 [3.20000000e+01 3.00000000e+00 3.00000000e+00 8.56736172e+08]
 [4.20000000e+01 3.00000000e+00 4.00000000e+00 9.96221045e+08]
 [4.30000000e+01 3.00000000e+00 5.00000000e+00 8.48994405e+08]
 [4.40000000e+01 3.00000000e+00 3.00000000e+00 8.69251910e+08]
 [5.10000000e+01 3.00000000e+00 4.00000000e+00 1.23093274e+09]
 [5.80000000e+01 3.00000000e+00 3.00000000e+00 8.47719397e+08]
 [6.40000000e+01 3.00000000e+00 3.50000000e+00 1.16151967e+09]
 [6.80000000e+01 3.00000000e+00 2.00000000e+00 1.15853342e+09]
 [9.10000000e+01 3.00000000e+00 3.00000000e+00 1.11271232e+09]
 [1.00000000e+02 3.00000000e+00 3.50000000e+00 1.10018380e+09]
 [1.02000000e+02 3.00000000e+00 5.00000000e+00 8.40635033e+08]
 [1.16000000e+02 3.00000000e+00 3.50000000e+00 1.33720032e+09]
 [1.17000000e+02 3.00000000e+00 3.00000000e+00 8.441636

In [0]:
ratings = npMovielens[npMovielens[:,1] == itemId, 2] # select all rating data based on movie id
print(ratings)

[4.  5.  3.  3.  4.  5.  3.  4.  3.  3.5 2.  3.  3.5 5.  3.5 3.  3.  3.
 5.  4.  1.  3.5 4.  4.  3.  4.  2.5 1.  3.  3.5 0.5 3.  3.  4.  3.  4.
 4.  3.  3.  3.  3.  2.5 4.  5.  3.  1.  5.  3.  3.  4.  1.5 2. ]


In [0]:
ratingAverage = ratings.mean()  # looking for average values in specific ratings list
print(ratingAverage)

3.2596153846153846


In [0]:
#print(users)

# users average ratings
for x in range(len(users)):
  userId = users[x]
  ratings = npMovielens[npMovielens[:,0] == userId, 2] # select all ratings by userid
  averageRating = ratings.mean()
  print(userId, averageRating)

1 4.366379310344827
2 3.9482758620689653
3 2.4358974358974357
4 3.5555555555555554
5 3.6363636363636362
6 3.4936305732484074
7 3.2302631578947367
8 3.574468085106383
9 3.260869565217391
10 3.2785714285714285
11 3.78125
12 4.390625
13 3.6451612903225805
14 3.3958333333333335
15 3.448148148148148
16 3.7244897959183674
17 4.20952380952381
18 3.7320717131474104
19 2.607396870554765
20 3.590909090909091
21 3.260722347629797
22 2.5714285714285716
23 3.6487603305785123
24 3.65
25 4.8076923076923075
26 3.238095238095238
27 3.5481481481481483
28 3.020175438596491
29 4.1419753086419755
30 4.735294117647059
31 3.92
32 3.7549019607843137
33 3.7884615384615383
34 3.4186046511627906
35 4.086956521739131
36 2.6333333333333333
37 4.142857142857143
38 3.217948717948718
39 4.0
40 3.766990291262136
41 3.2534562211981566
42 3.565909090909091
43 4.552631578947368
44 3.3541666666666665
45 3.8759398496240602
46 4.0
47 3.0535714285714284
48 4.03030303030303
49 4.261904761904762
50 2.7806451612903227
51 3.7757

In [0]:
#print(items)

# items average ratings
for x in range(len(items)):
  itemId = items[x]
  ratings = npMovielens[npMovielens[:,1] == itemId, 2] # select all ratings by userid
  averageRating = ratings.mean()
  print(itemId, averageRating)

Streaming output truncated to the last 5000 lines.
141004 3.25
165551 4.5
52319 3.5714285714285716
70599 3.9
71530 3.0357142857142856
77866 3.1666666666666665
95088 3.75
96737 3.7142857142857144
97306 3.466666666666667
112515 4.5
115122 4.833333333333333
121231 4.125
144976 4.5
69306 3.1666666666666665
81782 3.357142857142857
112171 3.2777777777777777
143458 4.0
501 3.6666666666666665
1844 3.875
3342 3.5
4082 3.5
4738 4.0
4864 2.5
5088 5.0
6902 4.0
7008 4.5
7265 3.730769230769231
8254 4.25
26681 4.0
27022 4.0
27482 3.75
33201 4.5
40148 3.357142857142857
43836 2.857142857142857
45440 3.3333333333333335
50842 4.5
55278 4.25
58301 4.375
63276 4.0
65130 3.7
65642 4.25
67695 2.625
69516 2.75
71304 4.0
71429 3.0
71520 2.3333333333333335
73488 2.0
75985 3.5
78218 3.0
79553 3.0
84952 4.0
86721 5.0
89190 1.75
90403 3.1666666666666665
91470 3.0
91690 3.6666666666666665
91947 4.5
92694 4.25
93855 4.5
94931 3.5
95690 4.5
95761 4.5
98607 4.5
99437 4.0
100882 4.75
101112 3.0833333333333335
107630 4.

In [0]:
df = df.pivot(index='user_id', columns='item_id', values='rating')

KeyError: ignored

In [0]:
def matrix_factorization(R, P, Q, K, steps=5, alpha=0.02, beta=0.2):
    Q = Q.T
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    eij = R[i][j] - np.dot(P[i,:],Q[:,j])
                    for k in range(K):
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])
        eR = np.dot(P,Q)
        e = 0
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    e = e + pow(R[i][j] - np.dot(P[i,:],Q[:,j]), 2)
                    for k in range(K):
                        e = e + (beta/2) * ( pow(P[i][k],2) + pow(Q[k][j],2) )
        if e < 0.001:
            break
    return P, Q.T

if __name__ == "__main__":
    df = df.fillna(0)
    R = df.to_numpy()

    N = len(R)
    M = len(R[0])
    K = 2

    P = np.random.rand(N,K)
    Q = np.random.rand(M,K)
    
    nP2, nQ2 = matrix_factorization(R, P, Q, K)
    
    print("the Original Matrix")
    print(R)
    print("the Approximation matrix by MF")
    print(np.dot(nP2, nQ2.T))

the Original Matrix
[[4.  0.  4.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 ...
 [2.5 2.  2.  ... 0.  0.  0. ]
 [3.  0.  0.  ... 0.  0.  0. ]
 [5.  0.  0.  ... 0.  0.  0. ]]
the Approximation matrix by MF
[[3.90933163 3.74727487 3.11304186 ... 2.70530653 2.66345242 3.43326129]
 [3.49889744 3.35427482 2.78885332 ... 2.4190748  2.38193093 3.06750852]
 [3.44674608 3.29802673 2.70792416 ... 2.4158543  2.37456008 3.10067858]
 ...
 [3.81373752 3.6549083  3.03229089 ... 2.64301532 2.60163154 3.35858512]
 [3.01694906 2.89892723 2.44676219 ... 2.05078207 2.02378027 2.56069252]
 [4.19209821 4.0231349  3.36852554 ... 2.8756961  2.83443738 3.62083532]]


In [0]:
if __name__ == "__main__":
    df = df.fillna(0)
    R = df.to_numpy()

    N = len(R)
    M = len(R[0])
    K = 5

    P = np.random.rand(N,K)
    Q = np.random.rand(M,K)
    
    nP5, nQ5 = matrix_factorization(R, P, Q, K)
    
    print("the Original Matrix")
    print(R)
    print("the Approximation matrix by MF")
    print(np.dot(nP5, nQ5.T))

the Original Matrix
[[4.  0.  4.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 ...
 [2.5 2.  2.  ... 0.  0.  0. ]
 [3.  0.  0.  ... 0.  0.  0. ]
 [5.  0.  0.  ... 0.  0.  0. ]]
the Approximation matrix by MF
[[3.9121406  3.7786506  3.13745824 ... 2.89084539 3.13030513 3.49520159]
 [3.50338966 3.42347938 2.98214816 ... 2.40842362 2.79828074 3.0688826 ]
 [3.30842162 3.20314848 2.75788481 ... 1.59477762 2.66877217 2.39561074]
 ...
 [3.87009986 3.76024299 3.2247615  ... 2.7297693  3.00765076 3.41399618]
 [3.11623328 3.06137644 2.4477176  ... 2.10807296 2.36973544 2.7825627 ]
 [4.16793939 4.02785545 3.28450547 ... 2.9317021  3.28105052 3.64573506]]


In [0]:
drivePrefix = '/content/gdrive/My Drive/'
driveSuffix = '1301170092_MF_Movielens/'
np.savetxt(drivePrefix+driveSuffix+'user_latent_features2.csv', nP2, delimiter=",")
np.savetxt(drivePrefix+driveSuffix+'item_latent_features2.csv', nQ2, delimiter=",")
np.savetxt(drivePrefix+driveSuffix+'user_latent_features5.csv', nP5, delimiter=",")
np.savetxt(drivePrefix+driveSuffix+'item_latent_features5.csv', nQ5, delimiter=",")

In [0]:
drivePrefix = '/content/gdrive/My Drive/'
driveSuffix = '1301170092_MF_Movielens/'

user_latent_features2 = np.loadtxt(drivePrefix+driveSuffix+'user_latent_features2.csv', delimiter=",")
item_latent_features2 = np.loadtxt(drivePrefix+driveSuffix+'item_latent_features2.csv', delimiter=",")
user_latent_features5 = np.loadtxt(drivePrefix+driveSuffix+'user_latent_features5.csv', delimiter=",")
item_latent_features5 = np.loadtxt(drivePrefix+driveSuffix+'item_latent_features5.csv', delimiter=",")

print(user_latent_features2)
print(item_latent_features2)
print(user_latent_features5)
print(item_latent_features5)

[[1.78865455 1.63824061]
 [1.58541401 1.48259335]
 [1.79178164 1.21715798]
 ...
 [1.77196195 1.56956754]
 [1.12130225 1.53836009]
 [1.74089827 1.94414108]]
[[1.17147817 1.10726218]
 [1.11030218 1.07513378]
 [0.85345174 0.968424  ]
 ...
 [0.87692232 0.69391237]
 [0.85489024 0.69241911]
 [1.18797702 0.79864995]]
[[0.89312365 1.11429986 1.15533011 1.1044568  0.96640657]
 [0.85456589 0.77943428 0.70770804 1.03962533 1.20839236]
 [1.60542478 0.26390086 0.31613127 0.31084666 1.56388013]
 ...
 [0.98327555 1.04166033 0.86153537 1.06980422 1.14685357]
 [1.14736846 0.80308199 0.59715447 0.84230256 0.72622137]
 [1.23316638 1.14037509 1.11549147 1.02316786 1.01522011]]
[[0.79750973 0.74443281 0.68526373 0.63641933 0.90618273]
 [0.81657266 0.65467668 0.56890968 0.77948152 0.82952866]
 [0.36434337 0.81008147 0.22943855 0.52439717 1.10215475]
 ...
 [0.2375023  0.77671029 0.5875433  0.68612396 0.38972993]
 [0.58926471 0.03896725 0.99353481 0.60129404 0.7746571 ]
 [0.61429773 0.74224785 0.45624817 1.02